### ISSUE TITLE
Error while installing dependencies with esy

### ISSUE THREAD

**Issue by davisuga** [aantron/dream#220] opened 2022-05-01 19:22 UTC
I got the following error when I run `esy` with the hello example:
```sh
 ~/gits/dream/example/1-hello | master !1 | esy                                                                                                     1 ✘  16:19:43 
info esy 0.6.12-dev (using esy.json)
info building @opam/easy-format@opam:1.3.3@f5b11eb6
error: build failed with exit code: 1
  build log:
    # esy-build-package: building: @opam/easy-format@opam:1.3.3
    # esy-build-package: pwd: /home/davi/.esy/3/b/opam__s__easy_format-opam__c__1.3.3-97ae9c63
    # esy-build-package: running: 'dune' 'build' '-p' 'easy-format' '-j' '4' '--promote-install-files=false' '@install'
    # esy-build-package: running: 'dune' 'install' '-p' 'easy-format' '--create-install-files' 'easy-format'
    /usr/bin/opam var prefix > /tmp/dune_0dfee4_output
    [ERROR] Opam has not been initialised, please run `opam init'
    error: command failed: 'dune' 'install' '-p' 'easy-format' '--create-install-files' 'easy-format' (exited with 1)
    esy-build-package: exiting with errors above...
    
  building @opam/easy-format@opam:1.3.3
esy: exiting due to errors above
```

**Comment by Et7f3** [comment] 2022-06-18 22:05
What is `master !1` ?

**Comment by davisuga** [comment] 2022-06-18 22:41
Oh, it's from my zsh config. Just ignore 😅

**Comment by aantron** [comment] 2023-04-16 06:20
I am unable to reproduce this locally right now. It looks like some kind of upstream error, probably in esy's repos, and it might have been fixed upstream. Have you observed this since?

**Comment by aantron** [comment] 2023-11-30 20:59
I'm going to close this for lack of information/ability to reproduce it. I've also converted the OCaml-syntax examples to use opam as the recommended package manager.

**Closed by aantron** 2023-11-30 20:59 UTC
Labels: 🤷‍♀️ upstream, 👀 needs repro
